### ISSUE TITLE
Why do we need to place a arrow left of the bow?

### ISSUE THREAD

**Issue by wzy2006** [AiTechEye/bows#4]
Can we  just put arrows in inventory?

**Comment by AiTechEye** [comment]
left of the bow, the opposite in minecraft

**Comment by AiTechEye** [comment]
if not? how would the bow know which arrow it should use?
if you wear a high explosive arrow you dont want to shoot it by mistake :)
But in real life you does same, the arrow front of the bow, and pushing it backwards untill the string is stretched.

but anyway, your question sounds like a good idea "auto mode", to avoid mess with different arrows.
i will take a look at this, probability a rightclick to enable/disable function

**Comment by AiTechEye** [comment]
done, place a bow to activate the mode
